### ISSUE TITLE
SHA-1 fingerprint for api.twilio.com needs updating

### ISSUE THREAD

**Issue by alexcchan** [TwilioDevEd/twilio_esp8266_arduino_example#1]
https://github.com/TwilioDevEd/twilio_esp8266_arduino_example/blob/master/twilio_esp8266_arduino_example.ino#L18

**Comment by openedhardware** [comment]
Open the terminal and try this:
```
echo | openssl s_client -connect api.twilio.com:443 | openssl x509 -fingerprint
```
You should get something like this:
![image](https://user-images.githubusercontent.com/16890683/42349245-ab765e86-80de-11e8-90d4-3a1a2342fe5e.png)

**Comment by pkamp3** [comment]
Sorry folks, and thank you!
