### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by Wolvezz7** [TwilioDevEd/twilio_esp8266_arduino_example#2]
I  am using twilio using nodemcu for the first time and I have encountered a problem. I tried running the sample code given along with this library and I get a message saying "Connection Failed" . When I looked this up in the library file "Twilio.cpp" , the condition is when the rest API is not connecting . I have not edited the host name (api.twilio.com) and the httpsPort (443). What am I missing here? As a matter of fact I had actually used the same code a week back and it worked perfectly. Please Help!!!!!!

**Comment by dursung** [comment]
I have same problem. there is something wrong api or port number ? when I put different api and port of a webserver connection sucsess.

**Comment by pkamp3** [comment]
Sorry about that @Wolvezz7 @dursung . If you're still looking, we just updated the code for the SSL library changes.

As long as you have the settings correct (and the fingerprint), this sample should be working again.
